import { expect, test } from '@playwright/test';
import { readFileSync } from 'node:fs';

/**
 * Design guarantees of the go/no-go stimulus selection, checked against the
 * committed manifest. These are properties of the SELECTION, not of the code
 * that produced it, so they hold whoever regenerates it and on whatever machine.
 *
 * Cue faces and practice faces are generated by the same script but answer to
 * different rules, and the one that matters most is that they never overlap: a
 * practice face that later appears as a cue would arrive already carrying a
 * learned action.
 */
const manifest = JSON.parse(
  readFileSync('tasks/go-no-go/sequences/stimuli-manifest.json', 'utf8')
);

test('cue faces: 24 per session, every model used once, fully balanced', () => {
  const allCue = manifest.sessions.flatMap((s) => s.faces.map((f) => f.model));
  expect(new Set(allCue).size, 'every cue model is used exactly once').toBe(allCue.length);

  for (const session of manifest.sessions) {
    expect(session.faces.length, `session ${session.session} has 24 cue faces`).toBe(24);

    const cells = {};
    for (const f of session.faces) {
      const key = `${f.ethnicity}${f.gender}|${f.affect}`;
      cells[key] = (cells[key] || 0) + 1;
    }
    // 2 ethnicities x 2 genders x 2 affects, 3 models each.
    expect(Object.keys(cells).length, `session ${session.session} fills 8 cells`).toBe(8);
    expect(
      Object.values(cells).every((n) => n === 3),
      `session ${session.session} has 3 models per cell: ${JSON.stringify(cells)}`
    ).toBe(true);
  }
});

test('practice faces: 4 neutral per session, balanced, never reused as cues', () => {
  const allCue = new Set(manifest.sessions.flatMap((s) => s.faces.map((f) => f.model)));
  const allPractice = manifest.sessions.flatMap((s) => s.practice.map((f) => f.model));

  expect(new Set(allPractice).size, 'practice models are distinct across sessions').toBe(
    allPractice.length
  );
  expect(
    allPractice.filter((m) => allCue.has(m)),
    'no practice model is also used as a cue - training must not teach a real cue'
  ).toEqual([]);

  for (const session of manifest.sessions) {
    const practice = session.practice;
    expect(practice.length, `session ${session.session} has 4 practice faces`).toBe(4);
    expect(
      practice.map((f) => f.gender).sort().join(''),
      `session ${session.session}: 2 female, 2 male`
    ).toBe('FFMM');
    expect(
      practice.map((f) => f.ethnicity).sort().join(''),
      `session ${session.session}: 2 Black, 2 White`
    ).toBe('BBWW');
    expect(
      [...new Set(practice.map((f) => f.affect))],
      `session ${session.session}: practice faces are neutral`
    ).toEqual(['neutral']);
  }
});
